// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using We_Doku.Data;

namespace We_Doku.Migrations.SudokuDb
{
    [DbContext(typeof(SudokuDbContext))]
    [Migration("20190314042041_username2")]
    partial class username2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("We_Doku.Models.GameBoard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Placed");

                    b.HasKey("ID");

                    b.ToTable("GameBoards");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Placed = 30
                        });
                });

            modelBuilder.Entity("We_Doku.Models.GameSpace", b =>
                {
                    b.Property<int>("GameBoardID");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.Property<bool>("Masked");

                    b.Property<int>("Value");

                    b.HasKey("GameBoardID", "X", "Y");

                    b.ToTable("GameSpaces");

                    b.HasData(
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 0,
                            Masked = false,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 0,
                            Masked = false,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 0,
                            Masked = true,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 0,
                            Masked = true,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 0,
                            Masked = false,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 0,
                            Masked = true,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 0,
                            Masked = true,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 0,
                            Masked = true,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 0,
                            Masked = true,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 1,
                            Masked = false,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 1,
                            Masked = true,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 1,
                            Masked = true,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 1,
                            Masked = false,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 1,
                            Masked = false,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 1,
                            Masked = false,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 1,
                            Masked = true,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 1,
                            Masked = true,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 1,
                            Masked = true,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 2,
                            Masked = true,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 2,
                            Masked = false,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 2,
                            Masked = false,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 2,
                            Masked = true,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 2,
                            Masked = true,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 2,
                            Masked = true,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 2,
                            Masked = true,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 2,
                            Masked = false,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 2,
                            Masked = true,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 3,
                            Masked = false,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 3,
                            Masked = true,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 3,
                            Masked = true,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 3,
                            Masked = true,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 3,
                            Masked = false,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 3,
                            Masked = true,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 3,
                            Masked = true,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 3,
                            Masked = true,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 3,
                            Masked = false,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 4,
                            Masked = false,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 4,
                            Masked = true,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 4,
                            Masked = true,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 4,
                            Masked = false,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 4,
                            Masked = true,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 4,
                            Masked = false,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 4,
                            Masked = true,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 4,
                            Masked = true,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 4,
                            Masked = false,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 5,
                            Masked = false,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 5,
                            Masked = true,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 5,
                            Masked = true,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 5,
                            Masked = true,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 5,
                            Masked = false,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 5,
                            Masked = true,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 5,
                            Masked = true,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 5,
                            Masked = true,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 5,
                            Masked = false,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 6,
                            Masked = true,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 6,
                            Masked = false,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 6,
                            Masked = true,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 6,
                            Masked = true,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 6,
                            Masked = true,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 6,
                            Masked = true,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 6,
                            Masked = false,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 6,
                            Masked = false,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 6,
                            Masked = true,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 7,
                            Masked = true,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 7,
                            Masked = true,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 7,
                            Masked = true,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 7,
                            Masked = false,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 7,
                            Masked = false,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 7,
                            Masked = false,
                            Value = 9
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 7,
                            Masked = true,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 7,
                            Masked = true,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 7,
                            Masked = false,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 0,
                            Y = 8,
                            Masked = true,
                            Value = 3
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 1,
                            Y = 8,
                            Masked = true,
                            Value = 4
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 2,
                            Y = 8,
                            Masked = true,
                            Value = 5
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 3,
                            Y = 8,
                            Masked = true,
                            Value = 2
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 4,
                            Y = 8,
                            Masked = false,
                            Value = 8
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 5,
                            Y = 8,
                            Masked = true,
                            Value = 6
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 6,
                            Y = 8,
                            Masked = true,
                            Value = 1
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 7,
                            Y = 8,
                            Masked = false,
                            Value = 7
                        },
                        new
                        {
                            GameBoardID = 1,
                            X = 8,
                            Y = 8,
                            Masked = false,
                            Value = 9
                        });
                });

            modelBuilder.Entity("We_Doku.Models.GameSpace", b =>
                {
                    b.HasOne("We_Doku.Models.GameBoard", "GameBoard")
                        .WithMany("GameSpaces")
                        .HasForeignKey("GameBoardID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
